# evaluating models after all training

We have 3 models on DNase, and want to test all of them

There's 2 for the cell type specific model that we should explore

In [1]:
#first we need to find the lowest validation loss for the multitasking model
import os
import numpy as np
file_list = []
name_list = []
for tempfile in os.listdir('/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-23/09-35-33-196632/checkpoints/'):
    # print(tempfile[-12:-5])
    file_list.append(tempfile)
    #now do a try except to see if the file is a float
    try:
        name_list.append(float(tempfile[-12:-5]))
    except:
        name_list.append(1000)
    # name_list.append(float(tempfile[-12:-5]))
        
#print the minimum of name list
print(min(name_list))
#find that index and print the file_list index
print(file_list[name_list.index(min(name_list))])

3.57483
381-val_loss=3.57483.ckpt


In [1]:
#we can use the ISM utils for this, as that is what we've been using for evaluation for explainability, so good to use this still
from evals.evals_utils import Evals
multitasking_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-23/09-35-33-196632/checkpoints/381-val_loss=3.57483.ckpt'
cts_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-29/15-45-02-282170/checkpoints/last.ckpt'
cts_path2 = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-09/17-38-16-568113/checkpoints/last.ckpt' #this is again the 10% 100 epochs one
ctst_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-23/09-35-11-173861/checkpoints/last.ckpt'


In [2]:
#let's try the ctst path
eval_ctst = Evals('DNase_ctst',ctst_path)

In [3]:
#now let's do evals
eval_ctst.evaluate(num_workers = 1, batch_size = 2048)
#yeah it seems to be working just fine! 

  0%|          | 0/8275 [00:00<?, ?it/s]

  3%|▎         | 287/8275 [06:08<2:50:54,  1.28s/it]


KeyboardInterrupt: 

In [3]:
#now let's try the multitasking path
eval_multitasking = Evals('DNase_allcelltypes',multitasking_path)

In [6]:
eval_multitasking.dataset.cell_types = 161 #a hack because misdefined it
eval_multitasking.evaluate(num_workers = 1, batch_size = 2048)
#161 times less data, so it does work out!

  0%|          | 0/52 [00:00<?, ?it/s]

100%|██████████| 52/52 [01:09<00:00,  1.33s/it]


(tensor([[-10.0000,  -0.4581, -10.0000,  ..., -10.0000,  -1.7576, -10.0000],
         [-10.0000,  -1.1888, -10.0000,  ..., -10.0000,  -3.0268,  -2.2397],
         [  0.2071,   1.3613,  -2.4325,  ...,  -0.7399,   4.2481,  -0.7007],
         ...,
         [  0.9784,   0.6225,   0.2469,  ...,   0.3363,   0.6615,  -0.4536],
         [  1.4823,   1.6966,   0.2309,  ...,   0.2233,   0.8615,  -0.2049],
         [  0.8997,   0.8567,   0.4843,  ...,   0.1876,   0.8940,  -1.0668]]),
 tensor([[-2.0285, -1.7535, -2.3377,  ..., -2.4311, -1.2368, -1.2885],
         [-3.5559, -3.0873, -3.0547,  ..., -2.6732, -0.8077, -1.1371],
         [-1.8445, -1.1222, -2.3453,  ..., -3.5471, -0.8294, -2.4889],
         ...,
         [ 0.0943,  0.0991,  0.4014,  ..., -0.3053,  0.1748,  0.2073],
         [ 1.2437,  1.4676,  0.4445,  ..., -0.0990,  0.8812,  0.2544],
         [ 0.5568,  0.6213,  0.4431,  ..., -0.5057,  0.3080,  0.3311]]))

In [11]:
#we see some values, let's just use that
a,b = eval_multitasking.dataset[0]
print(b) #exact same labels, at least what is shown, now let's see the predicitons

tensor([-1.0000e+01, -4.5808e-01, -1.0000e+01, -1.0000e+01, -1.8792e+00,
        -1.0000e+01, -2.3478e+00, -1.8173e+00, -6.1973e-01, -3.1970e+00,
        -3.1362e+00, -6.3732e-01, -1.0000e+01, -1.0000e+01, -1.0000e+01,
        -1.0000e+01, -1.0000e+01, -1.0000e+01, -1.0000e+01, -1.6359e+00,
        -2.9812e+00, -1.0000e+01, -1.0000e+01, -1.9674e+00, -1.0000e+01,
        -1.0000e+01, -1.0000e+01, -1.1343e+00, -1.4971e+00, -1.0000e+01,
        -1.0000e+01, -1.0000e+01, -1.6084e+00, -1.0000e+01, -1.0000e+01,
        -2.0236e+00, -2.5367e+00, -1.1614e-01, -5.7076e-01, -1.0000e+01,
        -1.0000e+01, -1.0000e+01, -1.0000e+01, -1.0000e+01, -1.0000e+01,
        -6.2989e-01, -1.0000e+01, -3.2462e-01, -1.0000e+01, -1.0000e+01,
        -1.0000e+01, -2.0274e-01, -1.0000e+01, -1.7594e+00, -1.0000e+01,
        -7.5590e-01, -1.1066e+00, -1.7550e+00, -1.0000e+01, -1.0000e+01,
        -1.2859e+00, -1.0000e+01, -4.0290e-02, -1.0000e+01, -5.8336e-01,
        -1.0000e+01, -1.0000e+01, -1.0000e+01, -1.0

In [13]:
temp,_ = eval_multitasking.backbone(a.unsqueeze(0).cuda())
out = eval_multitasking.decoder(temp)
print(out.shape)
print(out)
#once again we can manually verify the begining and last 3 are identical, so this means our model is good!!

torch.Size([1, 161])
tensor([[-2.0285, -1.7535, -2.3377, -1.0759, -1.6841, -1.4012, -0.8913, -0.6950,
         -1.3474, -0.6109, -0.7014, -1.0829, -1.6052, -0.5472, -1.0905, -1.4953,
         -1.6828, -1.0294, -1.9775, -0.5552, -1.5356, -1.3920, -1.9695, -2.0644,
         -1.5830, -2.4532, -0.8513, -1.6068, -1.3586, -2.7661, -0.8429, -2.1444,
         -1.3913, -2.9047, -1.9589, -1.3889, -1.7917, -0.2223, -3.0429, -2.7787,
         -3.8464, -4.3981, -2.6890, -3.3632, -5.7655, -1.8744, -2.4023, -2.7644,
         -1.3747, -3.3157, -3.5665, -0.7733, -1.8525, -0.4034, -2.2569, -1.2688,
         -1.0485, -1.3464, -1.4851, -2.9671, -0.7305, -0.8996, -1.9522, -1.0046,
         -2.1862, -0.5593, -0.5569, -1.5593, -2.8010, -3.7193, -2.6134, -0.6727,
         -3.8209, -1.7621, -0.9491, -1.2655, -1.0223, -1.3570, -4.0295, -3.6925,
         -4.4448, -0.5188, -1.0054, -0.8318, -0.9717, -1.0878,  0.2433, -2.1715,
         -1.1041, -0.9827, -3.2571, -1.4903, -1.2402, -3.7635, -0.9459, -3.5869,
       

In [15]:
#let's do it again for the second input, here's the expected
# target [-10.0000,  -1.1888, -10.0000,  ..., -10.0000,  -3.0268,  -2.2397],
# output [-3.5559, -3.0873, -3.0547,  ..., -2.6732, -0.8077, -1.1371],
a,b = eval_multitasking.dataset[1]
print(b) #exact same labels, at least what is shown, now let's see the predicitons
temp,_ = eval_multitasking.backbone(a.unsqueeze(0).cuda())
out = eval_multitasking.decoder(temp)
print(out.shape)
print(out)
#once again completely identical, so I think it's safe to say this model is fine

tensor([-10.0000,  -1.1888, -10.0000,  -2.6834, -10.0000, -10.0000, -10.0000,
        -10.0000, -10.0000,  -3.1970,  -3.1362,  -0.6400, -10.0000,  -2.7933,
        -10.0000, -10.0000, -10.0000, -10.0000, -10.0000,  -2.9364, -10.0000,
        -10.0000, -10.0000, -10.0000, -10.0000, -10.0000, -10.0000, -10.0000,
        -10.0000, -10.0000,  -1.9988, -10.0000, -10.0000, -10.0000, -10.0000,
         -2.0236,  -2.5367, -10.0000, -10.0000,  -0.6557, -10.0000, -10.0000,
        -10.0000, -10.0000, -10.0000,  -0.4904, -10.0000, -10.0000, -10.0000,
        -10.0000, -10.0000,   1.0666,   0.1828,   0.7807,  -0.4622,  -0.5024,
         -1.3944, -10.0000, -10.0000, -10.0000,  -1.4567,  -1.5473,   0.2794,
         -1.5674,   0.1411,  -1.2771,  -1.8280,  -1.3054, -10.0000, -10.0000,
        -10.0000,  -1.2153, -10.0000, -10.0000,  -1.3412,  -1.8704, -10.0000,
        -10.0000, -10.0000, -10.0000, -10.0000,  -2.5884, -10.0000,  -1.2475,
         -0.9299,  -1.9488,  -0.5997,  -1.9992,  -0.9325, -10.00

# final tests

In [1]:
#we will break the ctst model and then evaluate the results to see if they are the same as running the data raw from the dataset.
#so do both models, check outputs are what we expect, and then we can move on to the next step

#we can use the ISM utils for this, as that is what we've been using for evaluation for explainability, so good to use this still
from evals.evals_utils import Evals
multitasking_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-23/09-35-33-196632/checkpoints/381-val_loss=3.57483.ckpt'
cts_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-29/15-45-02-282170/checkpoints/last.ckpt'
cts_path2 = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-09/17-38-16-568113/checkpoints/last.ckpt' #this is again the 10% 100 epochs one
ctst_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-23/09-35-11-173861/checkpoints/last.ckpt'

#let's try the ctst path
eval_ctst = Evals('DNase_ctst',ctst_path)
#now let's do evals
outs = eval_ctst.evaluate(num_workers = 1, batch_size = 2048)
#yeah it seems to be working just fine! 
print(outs)

  0%|          | 5/8275 [00:09<4:11:46,  1.83s/it]


(tensor([[-10.0000,  -0.4581, -10.0000,  ..., -10.0000,  -1.7576, -10.0000],
        [-10.0000,  -1.1888, -10.0000,  ..., -10.0000,  -3.0268,  -2.2397],
        [  0.2071,   1.3613,  -2.4325,  ...,  -0.7399,   4.2481,  -0.7007],
        ...,
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000]]), tensor([[ 0.8877,  0.8289,  0.6171,  ...,  0.8529,  0.9480,  1.1287],
        [-3.2399, -2.5506, -2.3602,  ..., -1.9085, -0.4064, -0.5675],
        [ 0.0562,  0.7432,  0.3454,  ...,  0.4906,  2.2379,  1.2410],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]))


In [2]:
#let's again manually verify the first and last 3
a,b = eval_ctst.dataset[0]
print(b)
temp,_ = eval_ctst.backbone(a.unsqueeze(0).cuda())
out = eval_ctst.decoder(temp)
print(out)

tensor([-10.])
tensor([[0.8877]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [5]:
out_list = []
target_list = []
for i in range(161):
    a,b = eval_ctst.dataset[i]
    temp,_ = eval_ctst.backbone(a.unsqueeze(0).cuda())
    out = eval_ctst.decoder(temp)
    target_list.append(b.item())
    # print(out)
    out_list.append(out.item())

In [4]:
out_list

[0.8877016305923462,
 0.8288659453392029,
 0.6171100735664368,
 1.0251190662384033,
 0.8650311827659607,
 1.0687533617019653,
 1.0536092519760132,
 1.0084726810455322,
 1.1312285661697388,
 1.091808795928955,
 1.0137736797332764,
 1.0664992332458496,
 1.0612125396728516,
 1.135503888130188,
 1.0520257949829102,
 0.7574980854988098,
 0.9037701487541199,
 0.8775949478149414,
 0.6452786326408386,
 1.0623294115066528,
 0.8897803425788879,
 0.8670477867126465,
 0.9691247344017029,
 0.9366050362586975,
 1.0489659309387207,
 0.44417253136634827,
 0.874826192855835,
 0.8417102098464966,
 1.0960173606872559,
 0.6833798289299011,
 1.027572512626648,
 0.44195127487182617,
 1.076371431350708,
 0.2882196307182312,
 0.9506875872612,
 1.101499319076538,
 1.0688049793243408,
 1.4491207599639893,
 0.3372284173965454,
 0.39476603269577026,
 -0.2145477533340454,
 -0.9650071859359741,
 0.19831526279449463,
 -0.11373310536146164,
 -1.6251115798950195,
 0.5751596093177795,
 0.2966262698173523,
 0.0961847305

In [6]:
target_list #once again perfect match, let's check the second ccre

[-10.0,
 -0.4580809772014618,
 -10.0,
 -10.0,
 -1.879201054573059,
 -10.0,
 -2.3478338718414307,
 -1.8173274993896484,
 -0.6197326183319092,
 -3.1969776153564453,
 -3.1362497806549072,
 -0.6373192667961121,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -1.6359361410140991,
 -2.9811601638793945,
 -10.0,
 -10.0,
 -1.9674078226089478,
 -10.0,
 -10.0,
 -10.0,
 -1.134278416633606,
 -1.4970508813858032,
 -10.0,
 -10.0,
 -10.0,
 -1.608433485031128,
 -10.0,
 -10.0,
 -2.0236284732818604,
 -2.536665678024292,
 -0.11614356935024261,
 -0.5707607865333557,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -0.6298944354057312,
 -10.0,
 -0.324618399143219,
 -10.0,
 -10.0,
 -10.0,
 -0.20274455845355988,
 -10.0,
 -1.759379506111145,
 -10.0,
 -0.7559024095535278,
 -1.106569528579712,
 -1.7550193071365356,
 -10.0,
 -10.0,
 -1.285852313041687,
 -10.0,
 -0.040289830416440964,
 -10.0,
 -0.5833625197410583,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -10.0,
 -0.7358813285827637

In [9]:
out_list = []
target_list = []
for i in range(161,322):
    a,b = eval_ctst.dataset[i]
    temp,_ = eval_ctst.backbone(a.unsqueeze(0).cuda())
    out = eval_ctst.decoder(temp)
    target_list.append(b.item())
    # print(out)
    out_list.append(out.item())
print(out_list)
print(target_list)
#great, again the exact results we were hoping for!!

[-3.2398972511291504, -2.550564765930176, -2.360163927078247, -1.5194250345230103, -2.008556365966797, -1.727140188217163, -1.656821370124817, -1.594294786453247, -2.4293134212493896, -1.534557580947876, -1.537028193473816, -2.547062635421753, -2.678487777709961, -1.2757834196090698, -1.4589704275131226, -2.978858232498169, -3.077796220779419, -2.7968521118164062, -3.453587770462036, -1.388540506362915, -1.872012734413147, -2.6339356899261475, -2.3298227787017822, -2.1010525226593018, -2.03116774559021, -3.107649564743042, -1.980186104774475, -3.30318284034729, -2.127579689025879, -3.684777021408081, -1.4978086948394775, -3.933847427368164, -1.2939006090164185, -3.728515863418579, -2.009373903274536, -1.1691880226135254, -1.8437838554382324, -0.0510450154542923, -3.1424453258514404, -2.839461088180542, -3.718681573867798, -4.261534214019775, -3.3418123722076416, -3.0252020359039307, -4.216183662414551, -2.4816091060638428, -2.0885581970214844, -3.054487943649292, -3.000681161880493, -3

In [3]:
#final test with the normal DNase model
# import pretty_errors
from evals.evals_utils import Evals
multitasking_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-23/09-35-33-196632/checkpoints/381-val_loss=3.57483.ckpt'
cts_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-29/15-45-02-282170/checkpoints/last.ckpt'
cts_path2 = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-09/17-38-16-568113/checkpoints/last.ckpt' #this is again the 10% 100 epochs one
ctst_path = '/data/leslie/sarthak/hyena/hyena-dna/outputs/2024-02-23/09-35-11-173861/checkpoints/last.ckpt'

#let's try the ctst path
eval_cts = Evals('DNase',cts_path, cfg = 'DNase_full.yaml')
#now let's do evals
outs = eval_cts.evaluate(num_workers = 1, batch_size = 2048)
#yeah it seems to be working just fine! 
print(outs)

  0%|          | 5/8275 [00:08<3:56:14,  1.71s/it]


(tensor([[-10.0000,  -0.4581, -10.0000,  ..., -10.0000,  -1.7576, -10.0000],
        [-10.0000,  -1.1888, -10.0000,  ..., -10.0000,  -3.0268,  -2.2397],
        [  0.2071,   1.3613,  -2.4325,  ...,  -0.7399,   4.2481,  -0.7007],
        ...,
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000]]), tensor([[ 0.4608,  0.1812, -0.1047,  ...,  0.4467,  0.4108,  0.7876],
        [-3.6945, -3.5483, -2.6489,  ..., -1.0422, -0.2208,  0.1486],
        [ 0.5602,  0.2501, -0.6051,  ..., -0.5439,  0.4893,  0.0056],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]))


In [4]:
out_list = []
target_list = []
for i in range(161):
    a,b = eval_cts.dataset[i]
    temp,_ = eval_cts.backbone(a.unsqueeze(0).cuda())
    out = eval_cts.decoder(temp)
    target_list.append(b.item())
    # print(out)
    out_list.append(out.item())
print(out_list)
print(target_list)
#again it's identical

[0.4607941508293152, 0.1811811774969101, -0.10472239553928375, 0.29314929246902466, 0.18910421431064606, 0.39730584621429443, 0.3942635655403137, 0.4120621085166931, 0.5110092163085938, 0.6531122922897339, 0.6351823806762695, 0.49672237038612366, 0.733195424079895, 0.6328740119934082, 0.6094671487808228, 0.2716315984725952, 0.3630925714969635, 0.40567511320114136, 0.13957206904888153, 0.645267128944397, 0.2515438199043274, 0.41526561975479126, 0.4243916869163513, 0.39014509320259094, 0.7317792177200317, -0.22715282440185547, 0.4914673864841461, 0.2307317554950714, 0.7316731214523315, 0.11366632580757141, 0.7488692998886108, -0.6944421529769897, 0.36057934165000916, -0.46730872988700867, 0.22033847868442535, 0.6183946132659912, 0.5576953887939453, 1.0357459783554077, -1.3381800651550293, -0.7081025838851929, -2.306936740875244, -2.5576529502868652, -1.4282139539718628, -1.6125112771987915, -3.744837522506714, -0.1413612961769104, -0.40741002559661865, -1.420728087425232, 0.0533326864242

In [5]:
out_list = []
target_list = []
for i in range(161,322):
    a,b = eval_cts.dataset[i]
    temp,_ = eval_cts.backbone(a.unsqueeze(0).cuda())
    out = eval_cts.decoder(temp)
    target_list.append(b.item())
    # print(out)
    out_list.append(out.item())
print(out_list)
print(target_list)
#again it's identical

[-3.6944572925567627, -3.5482840538024902, -2.6488823890686035, -1.5765224695205688, -2.0324881076812744, -1.9059442281723022, -1.935296893119812, -1.8656620979309082, -2.807563304901123, -1.7708081007003784, -1.7910076379776, -2.974327564239502, -3.157135009765625, -1.4886542558670044, -1.6838747262954712, -3.262155532836914, -3.2835679054260254, -3.0905637741088867, -3.900477886199951, -1.6204434633255005, -2.0744025707244873, -3.1481966972351074, -2.687521457672119, -2.5804500579833984, -2.1136252880096436, -4.300700664520264, -2.3060755729675293, -3.5245251655578613, -2.606001138687134, -4.313931941986084, -1.5561338663101196, -4.34887170791626, -2.220216989517212, -5.105462551116943, -2.5611324310302734, -1.5914322137832642, -1.86241614818573, 0.3044491112232208, -3.1939897537231445, -2.222928047180176, -3.2100372314453125, -3.5089094638824463, -2.8917698860168457, -2.4294347763061523, -3.883242130279541, -1.6462360620498657, -1.343845009803772, -2.3092904090881348, -1.33962595462

In [7]:
outs[0].shape #it's a tensor, so we can just use torch.save to save it out!!

torch.Size([105252, 161])

# now testing the evaluations

Firwst load in the models nad make sure targets are identical

Then do some similar plots to compare the 4 models,  and find the global mse and stuff liek that