we have the data in tensor format but we need to figure out how the data is formatted and shape it. See the dataset for more, but we basically wanted to see how to shape things

Here's some code I used to test you can look at

```console
>>> import numpy as np
>>> seqs = np.load('/data1/lesliec/sarthak/data/GraphReg/torchdata/seq.npy')
seqs.shape
>>> seqs.shape
(1451, 6000000)
>>> seqs[0]
array([11, 11, 11, ...,  9,  8, 10], dtype=int8)
>>> y = np.load('/data1/lesliec/sarthak/data/GraphReg/torchdata/y_GM12878.npy')
>>> 
>>> y.shape
(1451, 60000)
>>> 6000000/600000
10.0
>>> 6000000/60000
100.0
>>> epi = np.load('/data1/lesliec/sarthak/data/GraphReg/torchdata/epi_GM12878.npy')
epi.sh>>> epi.shape
(1451, 180000)
>>> 6000000/180000
33.333333333333336
>>> y.shape
(1451, 60000)
>>> 50/49
1.0204081632653061
>>> 50//49
1
>>> seqs.shape
(1451, 6000000)
>>> import torch
>>> torch.arange(5)
tensor([0, 1, 2, 3, 4])
>>> shape = (60,10)
>>> tensor = torch.arange(torch.prod(torch.tensor(shape))).reshape(shape)
>>> shape
(60, 10)
>>> tensor
tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
        [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
        [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
        [190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
        [200, 201, 202, 203, 204, 205, 206, 207, 208, 209],
        [210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
        [220, 221, 222, 223, 224, 225, 226, 227, 228, 229],
        [230, 231, 232, 233, 234, 235, 236, 237, 238, 239],
        [240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
        [250, 251, 252, 253, 254, 255, 256, 257, 258, 259],
        [260, 261, 262, 263, 264, 265, 266, 267, 268, 269],
        [270, 271, 272, 273, 274, 275, 276, 277, 278, 279],
        [280, 281, 282, 283, 284, 285, 286, 287, 288, 289],
        [290, 291, 292, 293, 294, 295, 296, 297, 298, 299],
        [300, 301, 302, 303, 304, 305, 306, 307, 308, 309],
        [310, 311, 312, 313, 314, 315, 316, 317, 318, 319],
        [320, 321, 322, 323, 324, 325, 326, 327, 328, 329],
        [330, 331, 332, 333, 334, 335, 336, 337, 338, 339],
        [340, 341, 342, 343, 344, 345, 346, 347, 348, 349],
        [350, 351, 352, 353, 354, 355, 356, 357, 358, 359],
        [360, 361, 362, 363, 364, 365, 366, 367, 368, 369],
        [370, 371, 372, 373, 374, 375, 376, 377, 378, 379],
        [380, 381, 382, 383, 384, 385, 386, 387, 388, 389],
        [390, 391, 392, 393, 394, 395, 396, 397, 398, 399],
        [400, 401, 402, 403, 404, 405, 406, 407, 408, 409],
        [410, 411, 412, 413, 414, 415, 416, 417, 418, 419],
        [420, 421, 422, 423, 424, 425, 426, 427, 428, 429],
        [430, 431, 432, 433, 434, 435, 436, 437, 438, 439],
        [440, 441, 442, 443, 444, 445, 446, 447, 448, 449],
        [450, 451, 452, 453, 454, 455, 456, 457, 458, 459],
        [460, 461, 462, 463, 464, 465, 466, 467, 468, 469],
        [470, 471, 472, 473, 474, 475, 476, 477, 478, 479],
        [480, 481, 482, 483, 484, 485, 486, 487, 488, 489],
        [490, 491, 492, 493, 494, 495, 496, 497, 498, 499],
        [500, 501, 502, 503, 504, 505, 506, 507, 508, 509],
        [510, 511, 512, 513, 514, 515, 516, 517, 518, 519],
        [520, 521, 522, 523, 524, 525, 526, 527, 528, 529],
        [530, 531, 532, 533, 534, 535, 536, 537, 538, 539],
        [540, 541, 542, 543, 544, 545, 546, 547, 548, 549],
        [550, 551, 552, 553, 554, 555, 556, 557, 558, 559],
        [560, 561, 562, 563, 564, 565, 566, 567, 568, 569],
        [570, 571, 572, 573, 574, 575, 576, 577, 578, 579],
        [580, 581, 582, 583, 584, 585, 586, 587, 588, 589],
        [590, 591, 592, 593, 594, 595, 596, 597, 598, 599]])
>>> shape = (6,10)
>>> tensor = torch.arange(torch.prod(torch.tensor(shape))).reshape(shape)
>>> tensor
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])
>>> tensor.reshape(2*tensor.shape[0],tensor.shape[1]/2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: reshape(): argument 'shape' failed to unpack the object at pos 2 with error "type must be tuple of ints,but got float"
>>> tensor.reshape(2*tensor.shape[0],tensor.shape[1]//2)
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]])
>>> tensor.reshape(2*tensor.shape[0],tensor.shape[1]//2).shape
torch.Size([12, 5])
>>> epi.shape
(1451, 180000)
>>> temp = epi[0]
>>> temp.shape
(180000,)
>>> temp.reshape(60,1000,3)
array([[[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]],

       ...,

       [[0.9482422 , 0.        , 0.19726562],
        [0.074646  , 0.        , 0.        ],
        [1.6777344 , 0.        , 0.59765625],
        ...,
        [0.45336914, 0.        , 0.38623047],
        [1.4335938 , 0.        , 1.5361328 ],
        [0.88378906, 0.        , 0.        ]],

       [[0.1427002 , 0.        , 0.03799438],
        [0.        , 0.        , 0.87597656],
        [0.        , 0.        , 0.3762207 ],
        ...,
        [0.        , 0.        , 0.07037354],
        [0.3161621 , 0.        , 0.8432617 ],
        [0.59765625, 0.        , 0.        ]],

       [[0.47558594, 0.        , 0.        ],
        [0.6669922 , 0.        , 0.        ],
        [0.8989258 , 0.        , 0.12878418],
        ...,
        [0.        , 0.        , 0.16369629],
        [0.8173828 , 0.        , 1.6054688 ],
        [0.09643555, 0.        , 0.14489746]]], dtype=float32)
>>> e = temp.reshape(60,1000,3)
>>> e.shape
(60, 1000, 3)
>>> e = temp.reshape(60000,3)
>>> e
array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       ...,
       [0.        , 0.        , 0.16369629],
       [0.8173828 , 0.        , 1.6054688 ],
       [0.09643555, 0.        , 0.14489746]], dtype=float32)
>>> e[0]
array([0., 0., 0.], dtype=float32)
>>> e[1]
array([0., 0., 0.], dtype=float32)
>>> e[2]
array([0., 0., 0.], dtype=float32)
>>> e[0,:100]
array([0., 0., 0.], dtype=float32)
>>> e.shape
(60000, 3)
>>> e[:,0]
array([0.        , 0.        , 0.        , ..., 0.        , 0.8173828 ,
       0.09643555], dtype=float32)
>>> e[:,1]
array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
>>> epi.shape
(1451, 180000)
>>> test = torch.arange(50).reshape(5,10)
>>> test
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])
>>> max_length = 5
>>> num_chunks = test.shape[1]//max_length
>>> test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks)
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]])
>>> test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: shape '[10, 5, 3]' is invalid for input of size 50
>>> test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks)
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]])
>>> test.reshape(num_chunks*test.shape[0]//3,test.shape[1]//num_chunks,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: shape '[3, 5, 3]' is invalid for input of size 50
>>> test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks)
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]])
>>> test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks//3,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: shape '[10, 1, 3]' is invalid for input of size 50
>>> test.shape[1]
10
>>> test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks//2,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: shape '[10, 2, 2]' is invalid for input of size 50
>>> test.shape[1]
10
>>> num_chunks
2
>>> test.shape[0]
5
>>> test = torch.arange(5*12).reshape(5,12)
>>> test
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])
>>> test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks)
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]])
>>> test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks//3,3)
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]],

        [[54, 55, 56],
         [57, 58, 59]]])
otestut = test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks//3,3)
>>> out
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]],

        [[54, 55, 56],
         [57, 58, 59]]])
>>> out.shape
torch.Size([10, 2, 3])
>>> out[...,3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 3 is out of bounds for dimension 1 with size 3
>>> out[...,0]
tensor([[ 0,  3],
        [ 6,  9],
        [12, 15],
        [18, 21],
        [24, 27],
        [30, 33],
        [36, 39],
        [42, 45],
        [48, 51],
        [54, 57]])
>>> test = torch.arange(180000).reshape(1,180000)
>>> test.shape
torch.Size([1, 180000])
>>> test
tensor([[     0,      1,      2,  ..., 179997, 179998, 179999]])
>>> out = test.reshape(60,1000,3)
>>> out
tensor([[[     0,      1,      2],
         [     3,      4,      5],
         [     6,      7,      8],
         ...,
         [  2991,   2992,   2993],
         [  2994,   2995,   2996],
         [  2997,   2998,   2999]],

        [[  3000,   3001,   3002],
         [  3003,   3004,   3005],
         [  3006,   3007,   3008],
         ...,
         [  5991,   5992,   5993],
         [  5994,   5995,   5996],
         [  5997,   5998,   5999]],

        [[  6000,   6001,   6002],
         [  6003,   6004,   6005],
         [  6006,   6007,   6008],
         ...,
         [  8991,   8992,   8993],
         [  8994,   8995,   8996],
         [  8997,   8998,   8999]],

        ...,

        [[171000, 171001, 171002],
         [171003, 171004, 171005],
         [171006, 171007, 171008],
         ...,
         [173991, 173992, 173993],
         [173994, 173995, 173996],
         [173997, 173998, 173999]],

        [[174000, 174001, 174002],
         [174003, 174004, 174005],
         [174006, 174007, 174008],
         ...,
         [176991, 176992, 176993],
         [176994, 176995, 176996],
         [176997, 176998, 176999]],

        [[177000, 177001, 177002],
         [177003, 177004, 177005],
         [177006, 177007, 177008],
         ...,
         [179991, 179992, 179993],
         [179994, 179995, 179996],
         [179997, 179998, 179999]]])
>>> out[...,0]
tensor([[     0,      3,      6,  ...,   2991,   2994,   2997],
        [  3000,   3003,   3006,  ...,   5991,   5994,   5997],
        [  6000,   6003,   6006,  ...,   8991,   8994,   8997],
        ...,
        [171000, 171003, 171006,  ..., 173991, 173994, 173997],
        [174000, 174003, 174006,  ..., 176991, 176994, 176997],
        [177000, 177003, 177006,  ..., 179991, 179994, 179997]])
>>> out[:,:,0].shape
torch.Size([60, 1000])
>>> out[:,:,1]
tensor([[     1,      4,      7,  ...,   2992,   2995,   2998],
        [  3001,   3004,   3007,  ...,   5992,   5995,   5998],
        [  6001,   6004,   6007,  ...,   8992,   8995,   8998],
        ...,
        [171001, 171004, 171007,  ..., 173992, 173995, 173998],
        [174001, 174004, 174007,  ..., 176992, 176995, 176998],
        [177001, 177004, 177007,  ..., 179992, 179995, 179998]])
>>> epi
array([[ 0.        ,  0.        ,  0.        , ...,  0.09643555,
         0.        ,  0.14489746],
       [ 0.        ,  0.        ,  0.        , ...,  2.2714844 ,
         0.        ,  2.0761719 ],
       [ 5.2460938 ,  1.9423828 ,  2.9667969 , ...,  0.6323242 ,
         0.        ,  0.86376953],
       ...,
       [ 1.2148438 ,  0.        ,  0.        , ...,  5.3828125 ,
         1.0351562 ,  0.07037354],
       [ 0.16894531,  0.        ,  1.4492188 , ...,  0.5498047 ,
         0.        ,  0.        ],
       [11.5390625 ,  2.0527344 ,  1.9003906 , ...,  0.        ,
         0.        ,  0.        ]], dtype=float32)
>>> epi.shape
(1451, 180000)
>>> num_chunks = 6000000/100000
>>> num_chunks
60.0
>>> epi.shape.prod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'prod'
>>> epi.shape.prod()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'prod'
>>> epi.shape.product()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'product'
>>> epi.shape
(1451, 180000)
>>> 
>>> test = torch.arange(epi.shape[0]*epi.shape[1]).reshape(epi.shape)
>>> test.shape
torch.Size([1451, 180000])
>>> test
tensor([[        0,         1,         2,  ...,    179997,    179998,
            179999],
        [   180000,    180001,    180002,  ...,    359997,    359998,
            359999],
        [   360000,    360001,    360002,  ...,    539997,    539998,
            539999],
        ...,
        [260640000, 260640001, 260640002,  ..., 260819997, 260819998,
         260819999],
        [260820000, 260820001, 260820002,  ..., 260999997, 260999998,
         260999999],
        [261000000, 261000001, 261000002,  ..., 261179997, 261179998,
         261179999]])
>>> out = test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks//3,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: reshape(): argument 'shape' (position 1) must be tuple of ints, but found element of type float at pos 0
>>> num_chunks
60.0
>>> num_chunks = int(num_chunks)
>>> out = test.reshape(num_chunks*test.shape[0],test.shape[1]//num_chunks//3,3)
>>> out.shape
torch.Size([87060, 1000, 3])
>>> out[0,:,0]
tensor([   0,    3,    6,    9,   12,   15,   18,   21,   24,   27,   30,   33,
          36,   39,   42,   45,   48,   51,   54,   57,   60,   63,   66,   69,
          72,   75,   78,   81,   84,   87,   90,   93,   96,   99,  102,  105,
         108,  111,  114,  117,  120,  123,  126,  129,  132,  135,  138,  141,
         144,  147,  150,  153,  156,  159,  162,  165,  168,  171,  174,  177,
         180,  183,  186,  189,  192,  195,  198,  201,  204,  207,  210,  213,
         216,  219,  222,  225,  228,  231,  234,  237,  240,  243,  246,  249,
         252,  255,  258,  261,  264,  267,  270,  273,  276,  279,  282,  285,
         288,  291,  294,  297,  300,  303,  306,  309,  312,  315,  318,  321,
         324,  327,  330,  333,  336,  339,  342,  345,  348,  351,  354,  357,
         360,  363,  366,  369,  372,  375,  378,  381,  384,  387,  390,  393,
         396,  399,  402,  405,  408,  411,  414,  417,  420,  423,  426,  429,
         432,  435,  438,  441,  444,  447,  450,  453,  456,  459,  462,  465,
         468,  471,  474,  477,  480,  483,  486,  489,  492,  495,  498,  501,
         504,  507,  510,  513,  516,  519,  522,  525,  528,  531,  534,  537,
         540,  543,  546,  549,  552,  555,  558,  561,  564,  567,  570,  573,
         576,  579,  582,  585,  588,  591,  594,  597,  600,  603,  606,  609,
         612,  615,  618,  621,  624,  627,  630,  633,  636,  639,  642,  645,
         648,  651,  654,  657,  660,  663,  666,  669,  672,  675,  678,  681,
         684,  687,  690,  693,  696,  699,  702,  705,  708,  711,  714,  717,
         720,  723,  726,  729,  732,  735,  738,  741,  744,  747,  750,  753,
         756,  759,  762,  765,  768,  771,  774,  777,  780,  783,  786,  789,
         792,  795,  798,  801,  804,  807,  810,  813,  816,  819,  822,  825,
         828,  831,  834,  837,  840,  843,  846,  849,  852,  855,  858,  861,
         864,  867,  870,  873,  876,  879,  882,  885,  888,  891,  894,  897,
         900,  903,  906,  909,  912,  915,  918,  921,  924,  927,  930,  933,
         936,  939,  942,  945,  948,  951,  954,  957,  960,  963,  966,  969,
         972,  975,  978,  981,  984,  987,  990,  993,  996,  999, 1002, 1005,
        1008, 1011, 1014, 1017, 1020, 1023, 1026, 1029, 1032, 1035, 1038, 1041,
        1044, 1047, 1050, 1053, 1056, 1059, 1062, 1065, 1068, 1071, 1074, 1077,
        1080, 1083, 1086, 1089, 1092, 1095, 1098, 1101, 1104, 1107, 1110, 1113,
        1116, 1119, 1122, 1125, 1128, 1131, 1134, 1137, 1140, 1143, 1146, 1149,
        1152, 1155, 1158, 1161, 1164, 1167, 1170, 1173, 1176, 1179, 1182, 1185,
        1188, 1191, 1194, 1197, 1200, 1203, 1206, 1209, 1212, 1215, 1218, 1221,
        1224, 1227, 1230, 1233, 1236, 1239, 1242, 1245, 1248, 1251, 1254, 1257,
        1260, 1263, 1266, 1269, 1272, 1275, 1278, 1281, 1284, 1287, 1290, 1293,
        1296, 1299, 1302, 1305, 1308, 1311, 1314, 1317, 1320, 1323, 1326, 1329,
        1332, 1335, 1338, 1341, 1344, 1347, 1350, 1353, 1356, 1359, 1362, 1365,
        1368, 1371, 1374, 1377, 1380, 1383, 1386, 1389, 1392, 1395, 1398, 1401,
        1404, 1407, 1410, 1413, 1416, 1419, 1422, 1425, 1428, 1431, 1434, 1437,
        1440, 1443, 1446, 1449, 1452, 1455, 1458, 1461, 1464, 1467, 1470, 1473,
        1476, 1479, 1482, 1485, 1488, 1491, 1494, 1497, 1500, 1503, 1506, 1509,
        1512, 1515, 1518, 1521, 1524, 1527, 1530, 1533, 1536, 1539, 1542, 1545,
        1548, 1551, 1554, 1557, 1560, 1563, 1566, 1569, 1572, 1575, 1578, 1581,
        1584, 1587, 1590, 1593, 1596, 1599, 1602, 1605, 1608, 1611, 1614, 1617,
        1620, 1623, 1626, 1629, 1632, 1635, 1638, 1641, 1644, 1647, 1650, 1653,
        1656, 1659, 1662, 1665, 1668, 1671, 1674, 1677, 1680, 1683, 1686, 1689,
        1692, 1695, 1698, 1701, 1704, 1707, 1710, 1713, 1716, 1719, 1722, 1725,
        1728, 1731, 1734, 1737, 1740, 1743, 1746, 1749, 1752, 1755, 1758, 1761,
        1764, 1767, 1770, 1773, 1776, 1779, 1782, 1785, 1788, 1791, 1794, 1797,
        1800, 1803, 1806, 1809, 1812, 1815, 1818, 1821, 1824, 1827, 1830, 1833,
        1836, 1839, 1842, 1845, 1848, 1851, 1854, 1857, 1860, 1863, 1866, 1869,
        1872, 1875, 1878, 1881, 1884, 1887, 1890, 1893, 1896, 1899, 1902, 1905,
        1908, 1911, 1914, 1917, 1920, 1923, 1926, 1929, 1932, 1935, 1938, 1941,
        1944, 1947, 1950, 1953, 1956, 1959, 1962, 1965, 1968, 1971, 1974, 1977,
        1980, 1983, 1986, 1989, 1992, 1995, 1998, 2001, 2004, 2007, 2010, 2013,
        2016, 2019, 2022, 2025, 2028, 2031, 2034, 2037, 2040, 2043, 2046, 2049,
        2052, 2055, 2058, 2061, 2064, 2067, 2070, 2073, 2076, 2079, 2082, 2085,
        2088, 2091, 2094, 2097, 2100, 2103, 2106, 2109, 2112, 2115, 2118, 2121,
        2124, 2127, 2130, 2133, 2136, 2139, 2142, 2145, 2148, 2151, 2154, 2157,
        2160, 2163, 2166, 2169, 2172, 2175, 2178, 2181, 2184, 2187, 2190, 2193,
        2196, 2199, 2202, 2205, 2208, 2211, 2214, 2217, 2220, 2223, 2226, 2229,
        2232, 2235, 2238, 2241, 2244, 2247, 2250, 2253, 2256, 2259, 2262, 2265,
        2268, 2271, 2274, 2277, 2280, 2283, 2286, 2289, 2292, 2295, 2298, 2301,
        2304, 2307, 2310, 2313, 2316, 2319, 2322, 2325, 2328, 2331, 2334, 2337,
        2340, 2343, 2346, 2349, 2352, 2355, 2358, 2361, 2364, 2367, 2370, 2373,
        2376, 2379, 2382, 2385, 2388, 2391, 2394, 2397, 2400, 2403, 2406, 2409,
        2412, 2415, 2418, 2421, 2424, 2427, 2430, 2433, 2436, 2439, 2442, 2445,
        2448, 2451, 2454, 2457, 2460, 2463, 2466, 2469, 2472, 2475, 2478, 2481,
        2484, 2487, 2490, 2493, 2496, 2499, 2502, 2505, 2508, 2511, 2514, 2517,
        2520, 2523, 2526, 2529, 2532, 2535, 2538, 2541, 2544, 2547, 2550, 2553,
        2556, 2559, 2562, 2565, 2568, 2571, 2574, 2577, 2580, 2583, 2586, 2589,
        2592, 2595, 2598, 2601, 2604, 2607, 2610, 2613, 2616, 2619, 2622, 2625,
        2628, 2631, 2634, 2637, 2640, 2643, 2646, 2649, 2652, 2655, 2658, 2661,
        2664, 2667, 2670, 2673, 2676, 2679, 2682, 2685, 2688, 2691, 2694, 2697,
        2700, 2703, 2706, 2709, 2712, 2715, 2718, 2721, 2724, 2727, 2730, 2733,
        2736, 2739, 2742, 2745, 2748, 2751, 2754, 2757, 2760, 2763, 2766, 2769,
        2772, 2775, 2778, 2781, 2784, 2787, 2790, 2793, 2796, 2799, 2802, 2805,
        2808, 2811, 2814, 2817, 2820, 2823, 2826, 2829, 2832, 2835, 2838, 2841,
        2844, 2847, 2850, 2853, 2856, 2859, 2862, 2865, 2868, 2871, 2874, 2877,
        2880, 2883, 2886, 2889, 2892, 2895, 2898, 2901, 2904, 2907, 2910, 2913,
        2916, 2919, 2922, 2925, 2928, 2931, 2934, 2937, 2940, 2943, 2946, 2949,
        2952, 2955, 2958, 2961, 2964, 2967, 2970, 2973, 2976, 2979, 2982, 2985,
        2988, 2991, 2994, 2997])
>>> out[1,:,0]
tensor([3000, 3003, 3006, 3009, 3012, 3015, 3018, 3021, 3024, 3027, 3030, 3033,
        3036, 3039, 3042, 3045, 3048, 3051, 3054, 3057, 3060, 3063, 3066, 3069,
        3072, 3075, 3078, 3081, 3084, 3087, 3090, 3093, 3096, 3099, 3102, 3105,
        3108, 3111, 3114, 3117, 3120, 3123, 3126, 3129, 3132, 3135, 3138, 3141,
        3144, 3147, 3150, 3153, 3156, 3159, 3162, 3165, 3168, 3171, 3174, 3177,
        3180, 3183, 3186, 3189, 3192, 3195, 3198, 3201, 3204, 3207, 3210, 3213,
        3216, 3219, 3222, 3225, 3228, 3231, 3234, 3237, 3240, 3243, 3246, 3249,
        3252, 3255, 3258, 3261, 3264, 3267, 3270, 3273, 3276, 3279, 3282, 3285,
        3288, 3291, 3294, 3297, 3300, 3303, 3306, 3309, 3312, 3315, 3318, 3321,
        3324, 3327, 3330, 3333, 3336, 3339, 3342, 3345, 3348, 3351, 3354, 3357,
        3360, 3363, 3366, 3369, 3372, 3375, 3378, 3381, 3384, 3387, 3390, 3393,
        3396, 3399, 3402, 3405, 3408, 3411, 3414, 3417, 3420, 3423, 3426, 3429,
        3432, 3435, 3438, 3441, 3444, 3447, 3450, 3453, 3456, 3459, 3462, 3465,
        3468, 3471, 3474, 3477, 3480, 3483, 3486, 3489, 3492, 3495, 3498, 3501,
        3504, 3507, 3510, 3513, 3516, 3519, 3522, 3525, 3528, 3531, 3534, 3537,
        3540, 3543, 3546, 3549, 3552, 3555, 3558, 3561, 3564, 3567, 3570, 3573,
        3576, 3579, 3582, 3585, 3588, 3591, 3594, 3597, 3600, 3603, 3606, 3609,
        3612, 3615, 3618, 3621, 3624, 3627, 3630, 3633, 3636, 3639, 3642, 3645,
        3648, 3651, 3654, 3657, 3660, 3663, 3666, 3669, 3672, 3675, 3678, 3681,
        3684, 3687, 3690, 3693, 3696, 3699, 3702, 3705, 3708, 3711, 3714, 3717,
        3720, 3723, 3726, 3729, 3732, 3735, 3738, 3741, 3744, 3747, 3750, 3753,
        3756, 3759, 3762, 3765, 3768, 3771, 3774, 3777, 3780, 3783, 3786, 3789,
        3792, 3795, 3798, 3801, 3804, 3807, 3810, 3813, 3816, 3819, 3822, 3825,
        3828, 3831, 3834, 3837, 3840, 3843, 3846, 3849, 3852, 3855, 3858, 3861,
        3864, 3867, 3870, 3873, 3876, 3879, 3882, 3885, 3888, 3891, 3894, 3897,
        3900, 3903, 3906, 3909, 3912, 3915, 3918, 3921, 3924, 3927, 3930, 3933,
        3936, 3939, 3942, 3945, 3948, 3951, 3954, 3957, 3960, 3963, 3966, 3969,
        3972, 3975, 3978, 3981, 3984, 3987, 3990, 3993, 3996, 3999, 4002, 4005,
        4008, 4011, 4014, 4017, 4020, 4023, 4026, 4029, 4032, 4035, 4038, 4041,
        4044, 4047, 4050, 4053, 4056, 4059, 4062, 4065, 4068, 4071, 4074, 4077,
        4080, 4083, 4086, 4089, 4092, 4095, 4098, 4101, 4104, 4107, 4110, 4113,
        4116, 4119, 4122, 4125, 4128, 4131, 4134, 4137, 4140, 4143, 4146, 4149,
        4152, 4155, 4158, 4161, 4164, 4167, 4170, 4173, 4176, 4179, 4182, 4185,
        4188, 4191, 4194, 4197, 4200, 4203, 4206, 4209, 4212, 4215, 4218, 4221,
        4224, 4227, 4230, 4233, 4236, 4239, 4242, 4245, 4248, 4251, 4254, 4257,
        4260, 4263, 4266, 4269, 4272, 4275, 4278, 4281, 4284, 4287, 4290, 4293,
        4296, 4299, 4302, 4305, 4308, 4311, 4314, 4317, 4320, 4323, 4326, 4329,
        4332, 4335, 4338, 4341, 4344, 4347, 4350, 4353, 4356, 4359, 4362, 4365,
        4368, 4371, 4374, 4377, 4380, 4383, 4386, 4389, 4392, 4395, 4398, 4401,
        4404, 4407, 4410, 4413, 4416, 4419, 4422, 4425, 4428, 4431, 4434, 4437,
        4440, 4443, 4446, 4449, 4452, 4455, 4458, 4461, 4464, 4467, 4470, 4473,
        4476, 4479, 4482, 4485, 4488, 4491, 4494, 4497, 4500, 4503, 4506, 4509,
        4512, 4515, 4518, 4521, 4524, 4527, 4530, 4533, 4536, 4539, 4542, 4545,
        4548, 4551, 4554, 4557, 4560, 4563, 4566, 4569, 4572, 4575, 4578, 4581,
        4584, 4587, 4590, 4593, 4596, 4599, 4602, 4605, 4608, 4611, 4614, 4617,
        4620, 4623, 4626, 4629, 4632, 4635, 4638, 4641, 4644, 4647, 4650, 4653,
        4656, 4659, 4662, 4665, 4668, 4671, 4674, 4677, 4680, 4683, 4686, 4689,
        4692, 4695, 4698, 4701, 4704, 4707, 4710, 4713, 4716, 4719, 4722, 4725,
        4728, 4731, 4734, 4737, 4740, 4743, 4746, 4749, 4752, 4755, 4758, 4761,
        4764, 4767, 4770, 4773, 4776, 4779, 4782, 4785, 4788, 4791, 4794, 4797,
        4800, 4803, 4806, 4809, 4812, 4815, 4818, 4821, 4824, 4827, 4830, 4833,
        4836, 4839, 4842, 4845, 4848, 4851, 4854, 4857, 4860, 4863, 4866, 4869,
        4872, 4875, 4878, 4881, 4884, 4887, 4890, 4893, 4896, 4899, 4902, 4905,
        4908, 4911, 4914, 4917, 4920, 4923, 4926, 4929, 4932, 4935, 4938, 4941,
        4944, 4947, 4950, 4953, 4956, 4959, 4962, 4965, 4968, 4971, 4974, 4977,
        4980, 4983, 4986, 4989, 4992, 4995, 4998, 5001, 5004, 5007, 5010, 5013,
        5016, 5019, 5022, 5025, 5028, 5031, 5034, 5037, 5040, 5043, 5046, 5049,
        5052, 5055, 5058, 5061, 5064, 5067, 5070, 5073, 5076, 5079, 5082, 5085,
        5088, 5091, 5094, 5097, 5100, 5103, 5106, 5109, 5112, 5115, 5118, 5121,
        5124, 5127, 5130, 5133, 5136, 5139, 5142, 5145, 5148, 5151, 5154, 5157,
        5160, 5163, 5166, 5169, 5172, 5175, 5178, 5181, 5184, 5187, 5190, 5193,
        5196, 5199, 5202, 5205, 5208, 5211, 5214, 5217, 5220, 5223, 5226, 5229,
        5232, 5235, 5238, 5241, 5244, 5247, 5250, 5253, 5256, 5259, 5262, 5265,
        5268, 5271, 5274, 5277, 5280, 5283, 5286, 5289, 5292, 5295, 5298, 5301,
        5304, 5307, 5310, 5313, 5316, 5319, 5322, 5325, 5328, 5331, 5334, 5337,
        5340, 5343, 5346, 5349, 5352, 5355, 5358, 5361, 5364, 5367, 5370, 5373,
        5376, 5379, 5382, 5385, 5388, 5391, 5394, 5397, 5400, 5403, 5406, 5409,
        5412, 5415, 5418, 5421, 5424, 5427, 5430, 5433, 5436, 5439, 5442, 5445,
        5448, 5451, 5454, 5457, 5460, 5463, 5466, 5469, 5472, 5475, 5478, 5481,
        5484, 5487, 5490, 5493, 5496, 5499, 5502, 5505, 5508, 5511, 5514, 5517,
        5520, 5523, 5526, 5529, 5532, 5535, 5538, 5541, 5544, 5547, 5550, 5553,
        5556, 5559, 5562, 5565, 5568, 5571, 5574, 5577, 5580, 5583, 5586, 5589,
        5592, 5595, 5598, 5601, 5604, 5607, 5610, 5613, 5616, 5619, 5622, 5625,
        5628, 5631, 5634, 5637, 5640, 5643, 5646, 5649, 5652, 5655, 5658, 5661,
        5664, 5667, 5670, 5673, 5676, 5679, 5682, 5685, 5688, 5691, 5694, 5697,
        5700, 5703, 5706, 5709, 5712, 5715, 5718, 5721, 5724, 5727, 5730, 5733,
        5736, 5739, 5742, 5745, 5748, 5751, 5754, 5757, 5760, 5763, 5766, 5769,
        5772, 5775, 5778, 5781, 5784, 5787, 5790, 5793, 5796, 5799, 5802, 5805,
        5808, 5811, 5814, 5817, 5820, 5823, 5826, 5829, 5832, 5835, 5838, 5841,
        5844, 5847, 5850, 5853, 5856, 5859, 5862, 5865, 5868, 5871, 5874, 5877,
        5880, 5883, 5886, 5889, 5892, 5895, 5898, 5901, 5904, 5907, 5910, 5913,
        5916, 5919, 5922, 5925, 5928, 5931, 5934, 5937, 5940, 5943, 5946, 5949,
        5952, 5955, 5958, 5961, 5964, 5967, 5970, 5973, 5976, 5979, 5982, 5985,
        5988, 5991, 5994, 5997])
>>> out.shape
torch.Size([87060, 1000, 3])
```