In [1]:
#we created the dataset, let's test it to see if it makes sense
import sys
sys.path.append('/data/leslie/sarthak/caduceus/')
import src.dataloaders.datasets.kmer_pretrain_dataset as kmer_pretrain_dataset
dataset = kmer_pretrain_dataset.KmerPretrain('train', 196608)

Using kmer genome with length 6


In [2]:
out = dataset[0]
print(out[0].shape)
print(out[1].shape)
print(out[0])
print(out[1])
print(dataset.tokenizer.decode(15629))

torch.Size([196608])
torch.Size([196608])
tensor([ 9406,   158,   790,  ..., 15628, 15628,   687])
tensor([15629, 15629, 15629,  ...,  6902,  3262, 15629])
[PAD]


In [3]:
out[1][:100]

tensor([15629, 15629, 15629,  3950, 15629, 15629, 15629, 15629, 15629, 15629,
        15629, 15629, 15629, 15629, 15629, 15629,  4126, 15629, 15629, 15629,
        15629, 15629, 15629, 15629, 15629, 15629, 15629, 15629,  4126, 15629,
        15629, 15629, 15629, 15629, 15629, 15629, 15629, 15629,   790, 15629,
        15629, 15629, 15629,   158, 15629, 15629, 15629,  5006, 15629, 15629,
        15629, 15629, 15629,  5006, 15629,   158, 15629, 15629, 15629, 15629,
        15629, 15629, 15629, 15629, 15629, 15629,  9406, 15629, 15629, 15629,
         4126, 15629, 15629, 15629, 15629, 15629, 15629, 15629, 15629, 15629,
        15629, 15629, 15629, 15629,  9406, 15629, 15629, 15629,  4126, 15629,
         9406, 15629, 15629, 15629, 15629,  5006, 15629, 15629, 15629, 15629])

In [4]:
out[0][:100]

tensor([ 9406,   158,   790, 15628,  4126,  5006,  9406,   158,   790,  3950,
         4126,  5006,  9406,   158,   790,  3950,  9515,  5006,  9406,   158,
          790,  3950,  4126,  5006,  9406,   158,   790,  3950, 15628,  5006,
         9406,   158,   790,  3950,  4126,  5006,  9406,   158, 15628,  3950,
         4126,  5006,  9406, 15628,   790,  3950,  4126,  5006,  9406,   158,
          790,  3950,  4126, 15628,  9406, 15628,   790,  3950,  4126,  5006,
         9406,   158,   790,  3950,  4126,  5006, 15628,   158,   790,  3950,
        15628,  5006,  9406,   158,   790,  3950,  4126,  5006,  9406,   158,
          790,  3950,  4126,  5006, 15628,   158,   790,  3950, 15628,  5006,
         9406,   158,   790,  3950,  4126, 15628,  9406,   158,   790,  3950])

In [5]:
#let's test mlm.get item
#so we produce a sequence, let's just get that sequence
idx = 0
peak = dataset.data[idx]
chrom = peak[0]
center = int(peak[1])
seq = dataset.genome[chrom][center-dataset.max_length//2:center+dataset.max_length//2]
print(len(seq))

196608


In [8]:
seq[:100]

array([9406,  158,  790, 3950, 4126, 5006, 9406,  158,  790, 3950, 4126,
       5006, 9406,  158,  790, 3950, 4126, 5006, 9406,  158,  790, 3950,
       4126, 5006, 9406,  158,  790, 3950, 4126, 5006, 9406,  158,  790,
       3950, 4126, 5006, 9406,  158,  790, 3950, 4126, 5006, 9406,  158,
        790, 3950, 4126, 5006, 9406,  158,  790, 3950, 4126, 5006, 9406,
        158,  790, 3950, 4126, 5006, 9406,  158,  790, 3950, 4126, 5006,
       9406,  158,  790, 3950, 4126, 5006, 9406,  158,  790, 3950, 4126,
       5006, 9406,  158,  790, 3950, 4126, 5006, 9406,  158,  790, 3950,
       4126, 5006, 9406,  158,  790, 3950, 4126, 5006, 9406,  158,  790,
       3950], dtype=int16)

In [9]:
#see seq is similar to the input data but slightly off
#let's see an instance where it's off is like 4
#there it's 3950, and that's what the target is, ahh as we expect
#this means it's likely correct, so let's just use it
#check number of elements in the tokenizer
print(len(dataset.tokenizer))


15632
